name: glslang

on: [push, pull_request]

# Cancel in-progress builds on push to same branch / PR
# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # If you want to get more angry, check the HELL OF A MESS over at
  # https://github.com/KhronosGroup/glslang/releases
  VERSION: 8.13.3743

jobs:
  ubuntu:
    name: ${{ matrix.os }}-gcc${{ matrix.env.GCC }}
    runs-on: ${{ matrix.runs-on }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
        - os: ubuntu-18.04
          runs-on: ubuntu-latest
          container: ubuntu:bionic-20220427
          env:
            GCC: 4.8
        - os: ubuntu-18.04
          runs-on: ubuntu-latest
          container: ubuntu:bionic-20220427
          env:
            GCC: 7
    steps:
    - name: Install base build tools
      # apt update is needed to fetch package lists
      run: |
        apt update
        apt install -y ninja-build cmake g++-${{ matrix.env.GCC }}
    - name: Clone glslang
      uses: actions/checkout@v3
      with:
        repository: KhronosGroup/glslang
        ref: ${{ env.VERSION }}
        # FUCKING HELL, why this isn't the default and why it implicitly clones
        # to magnum-ci?! what the fuck?!
        path: glslang
    - name: Build & install
      # Why am I not surprised that this enables tests and other useless shit
      # by default. I'm not interested in anything related to spirv-tools here
      # because I'm doing that myself, better.
      run: |
        mkdir build && cd build
        cmake ../glslang \
          -DCMAKE_C_COMPILER=gcc-${{ matrix.env.GCC }} \
          -DCMAKE_CXX_COMPILER=g++-${{ matrix.env.GCC }} \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=$(pwd)/../install \
          -DBUILD_TESTING=OFF \
          -DBUILD_EXTERNAL=OFF \
          -DENABLE_CTEST=OFF \
          -DENABLE_GLSLANG_BINARIES=OFF \
          -DENABLE_OPT=OFF \
          -DENABLE_SPVREMAPPER=OFF \
          -G Ninja
        ninja install/strip
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: glslang-${{ env.VERSION }}-${{ matrix.os }}-gcc${{ matrix.env.GCC }}
        path: install

  windows:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3
    - name: Set up Visual Studio environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v3
    - name: Clone glslang
      uses: actions/checkout@v3
      with:
        repository: KhronosGroup/glslang
        ref: ${{ env.VERSION }}
        # FUCKING HELL, why this isn't the default and why it implicitly clones
        # to magnum-ci?! what the fuck?!
        path: glslang
    - name: Build & install Debug
      shell: cmd
      # -S and -B is only since CMake 3.13, Windows 2016 uses 3.12 even though
      # the README says 3.19.1
      run: |
        mkdir build-debug && cd build-debug
        cmake ../glslang ^
          -DCMAKE_C_COMPILER=cl.exe ^
          -DCMAKE_CXX_COMPILER=cl.exe ^
          -DCMAKE_BUILD_TYPE=Debug ^
          -DCMAKE_DEBUG_POSTFIX=-d ^
          -DCMAKE_INSTALL_PREFIX=%CD:\=/%/../install-debug ^
          -DBUILD_TESTING=OFF ^
          -DBUILD_EXTERNAL=OFF ^
          -DENABLE_CTEST=OFF ^
          -DENABLE_GLSLANG_BINARIES=OFF ^
          -DENABLE_OPT=OFF ^
          -DENABLE_SPVREMAPPER=OFF ^
          -G Ninja
        ninja install
    - name: Build & install Release
      shell: cmd
      # -S and -B is only since CMake 3.13, Windows 2016 uses 3.12 even though
      # the README says 3.19.1
      run: |
        mkdir build && cd build
        cmake ../glslang ^
          -DCMAKE_C_COMPILER=cl.exe ^
          -DCMAKE_CXX_COMPILER=cl.exe ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DCMAKE_INSTALL_PREFIX=%CD:\=/%/../install ^
          -DBUILD_TESTING=OFF ^
          -DBUILD_EXTERNAL=OFF ^
          -DENABLE_CTEST=OFF ^
          -DENABLE_GLSLANG_BINARIES=OFF ^
          -DENABLE_OPT=OFF ^
          -DENABLE_SPVREMAPPER=OFF ^
          -G Ninja
        ninja install
    - name: Upload Debug artifacts
      uses: actions/upload-artifact@v1
      with:
        name: glslang-${{ env.VERSION }}-${{ matrix.os }}-debug
        path: install-debug
    - name: Upload Release artifacts
      uses: actions/upload-artifact@v1
      with:
        name: glslang-${{ env.VERSION }}-${{ matrix.os }}
        path: install
