name: libwebp

on: [push, pull_request]

# Cancel in-progress builds on push to same branch / PR
# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  WEBP_VERSION: 1.3.1

jobs:
  ubuntu:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
        - os: ubuntu-18.04
          runs-on: ubuntu-latest
          container: ubuntu:bionic-20220427
    steps:
    - name: Install base build tools
      run: |
        apt update
        apt install -y ninja-build cmake g++
        mkdir -p deps
    - name: Clone libwebp
      uses: actions/checkout@v3
      with:
        repository: webmproject/libwebp
        ref: v${{ env.WEBP_VERSION }}
        path: libwebp
    - name: Build & install
      run: |
        mkdir build && cd build
        cmake ../libwebp \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=$(pwd)/../install \
          -DWEBP_LINK_STATIC=ON \
          -DWEBP_BUILD_ANIM_UTILS=OFF \
          -DWEBP_BUILD_CWEBP=OFF \
          -DWEBP_BUILD_DWEBP=OFF \
          -DWEBP_BUILD_GIF2WEBP=OFF \
          -DWEBP_BUILD_IMG2WEBP=OFF \
          -DWEBP_BUILD_VWEBP=OFF \
          -DWEBP_BUILD_WEBPINFO=OFF \
          -DWEBP_BUILD_LIBWEBPMUX=OFF \
          -DWEBP_BUILD_WEBPMUX=OFF \
          -DWEBP_BUILD_EXTRAS=OFF \
          -G Ninja
        ninja install/strip
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: libwebp-${{ env.WEBP_VERSION }}-${{ matrix.os }}
        path: install
