name: SDL

on: [push, pull_request]

env:
  SDL_VERSION: 2.28.5

jobs:
  ubuntu:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
        - os: ubuntu-18.04
          runs-on: ubuntu-latest
          container: ubuntu:bionic-20220427
    steps:
    - name: Install base build tools
      run: |
        apt update
        apt install -y ninja-build cmake g++ libgl1-mesa-dev
    - name: Clone SDL
      uses: actions/checkout@v3
      with:
        repository: libsdl-org/SDL
        path: sdl
        ref: release-${{ env.SDL_VERSION }}
    - name: Build & install
      run: |
        mkdir sdl-build && cd sdl-build
        cmake ../sdl \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=$(pwd)/../install \
          -DSDL_ATOMIC=OFF \
          -DSDL_CPUINFO=OFF \
          -DSDL_FILE=OFF \
          -DSDL_FILESYSTEM=OFF \
          -DSDL_HAPTIC=OFF \
          -DSDL_LOCALE=OFF \
          -DSDL_POWER=OFF \
          -DSDL_RENDER=OFF \
          -DSDL_SENSOR=OFF \
          -DSDL_SHARED=OFF \
          `# Needed so it can be linked to a *.so for Magnum Python Bindings` \
          -DSDL_STATIC_PIC=ON \
          -G Ninja
        ninja install/strip
    - name: Remove sdl2-config binary, M4 and pkgconfig cruft
      run: |
        rm -r install/bin
        rm -r install/lib/pkgconfig
        rm -r install/share
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sdl-${{ env.SDL_VERSION }}-${{ matrix.os }}
        path: install
